# kubectl apply -f manifest.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: mydb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: default
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: ambesh333/todo-devops # Replace with your todo backend image
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:mysecretpassword@postgres-service:5432/mydb?sslmode=disable
            - name: JWT_SECRET
              value: todo

---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: default
spec:
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

---
# To use this forward the port using this command and access on 8080
# kubectl port-forward service/todo-service 8080:3000

apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: default
spec:
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
  type: NodePort
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: web-apps-ingress
#   namespace: default
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   ingressClassName: nginx
#   rules:
#     - host: ambesh.com # Replace with your actual domain or IP address
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: todo-service
#                 port:
#                   number: 3000

# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-ingress-controller
#   namespace: default
# spec:
#   type: NodePort
#   selector:
#     app.kubernetes.io/name: ingress-nginx
#   ports:
#     - name: http
#       port: 80
#       targetPort: 80
#       nodePort: 30080  # Optionally specify a NodePort
#     - name: https
#       port: 443
#       targetPort: 443
#       nodePort: 30443  # Optionally specify a NodePort

